pipeline{
    agent none
    stages{
        stage('Maven Build'){
            agent {
                docker { image 'maven:3.8.1-adoptjdk-11'}
            }
            steps{
              sh 'mvn --version'
              sh 'java --version'
            }
        }
    }
    stages{
        stage('Node Build'){
            agent {
                docker { image 'node:16-alpine'}
            }
            steps{
              sh 'node --version'
            }
        }
    }
}