pipeline{
    agent none
    stages{
        stage('Maven Build'){
            agent {
                docker { image 'maven:3-eclipse-temurin-11-alpine'}
            }
            steps{
              sh 'mvn --version'
              sh 'java --version'
            }
        }
        
        stage('Node Build'){
            agent {
                docker { image 'node:16-alpine'}
            }
            steps{
              sh 'node --version'
            }
        }
    }
}